### ISSUE TITLE
Consider RTTrPM/RTTrPL

### ISSUE THREAD

**Issue by peternewman** [sandinak/dmx-followspot#4]
https://rttrp.github.io/RTTrP-Wiki/RTTrPL.html

It's in a similar area and may be of use.

**Comment by sandinak** [comment]
This looks interesting .. and might be a good integration long term. I looked into "automated" tracking via several methods: radio, camera, camera+marker, ultrasonic, etc.. and most of the issues with using them were cost-prohibitive for me ;) or could be impacted by stage environments in ways that made them un-useful.  .. If someone wants to integrate i am all about it .. I'd just want to see an application where it'd be useful before I jump thru those hoops.
